# paperback: paper backup generator suitable for long-term storage
# Copyright (C) 2018-2022 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs: {}

name: binaries

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
          - armv5te-unknown-linux-musleabi

    steps:
    - uses: actions/checkout@v5
    
    - uses: houseabsolute/actions-rust-cross@v1
      with:
        command: build
        target: ${{ matrix.target }}
        args: "--release --all-features"
        strip: true
        
    - name: upload unix binaries
      uses: actions/upload-artifact@v4
      if: "!contains(matrix.target, 'windows')"
      with:
        name: "paperback.${{ matrix.target }}"
        path: "target/${{ matrix.target }}/release/paperback"
        
    - name: upload windows binaries
      uses: actions/upload-artifact@v4
      if: contains(matrix.target, 'windows')
      with:
        name: "paperback-${{ matrix.target }}.exe"
        path: "target/${{ matrix.target }}/release/paperback.exe"
