# paperback: paper backup generator suitable for long-term storage
# Copyright (C) 2018-2022 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs: {}

name: binaries

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, win-msvc, win32-msvc, linux-arm64, linux-armv7, linux-armv6, linux-armv5]
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-2025
          target: x86_64-pc-windows-msvc
        - build: win32-msvc
          os: windows-2025
          target: i686-pc-windows-msvc
        - build: linux-arm64
          os: ubuntu-latest
          target: aarch64-unknown-linux-musl
        - build: linux-armv7
          os: ubuntu-latest
          target: armv7-unknown-linux-musleabihf
        - build: linux-armv6
          os: ubuntu-latest
          target: arm-unknown-linux-musleabihf
        - build: linux-armv5
          os: ubuntu-latest
          target: armv5te-unknown-linux-musleabi

    steps:
    - uses: actions/checkout@v5
    - run: rustup toolchain install stable
    - run: rustup target add ${{ matrix.target }}
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: cargo build
      run: cargo build --target ${{ matrix.target }} --release --all-features
    - name: strip paperback binary
      if: matrix.build == 'linux' || matrix.build == 'macos' || matrix.build == 'linux-arm64' || matrix.build == 'linux-armv7' || matrix.build == 'linux-armv6' || matrix.build == 'linux-armv5'
      run: strip target/${{ matrix.target }}/release/paperback
    - name: upload unix binaries
      uses: actions/upload-artifact@v4
      if: contains(matrix.build, 'win') == false
      with:
        name: "paperback.${{ matrix.target }}"
        path: "target/${{ matrix.target }}/release/paperback"
    - name: upload windows binaries
      uses: actions/upload-artifact@v4
      if: contains(matrix.build, 'win')
      with:
        name: "paperback-${{ matrix.target }}.exe"
        path: "target/${{ matrix.target }}/release/paperback.exe"
